sudo: required
language: c
dist: xenial

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - echo "${DOCKER_PASSWORD}" | docker login -u $DOCKER_USER --password-stdin
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform linux/armhf --oci-worker-platform linux/arm64
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - sudo mkdir -m 777 /build
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234
  
script:
  - if git describe --contains ${TRAVIS_COMMIT} &>/dev/null; then VERSION="$(git describe --contains ${TRAVIS_COMMIT})"; else VERSION="dev"; fi; export VERSION
  - ./.travis/build-all.sh

after_success:
  - sudo chmod -R a+rw /build
  - ./.travis/post-build.sh
  - sudo chmod a+rx /tmp/deploy_containers.sh
    
deploy:
  - provider: releases
    skip_cleanup: true
    api-key:
       secure: $GITHUB_TOKEN
    file: /build/dnsdock.amd64
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api-key:
       secure: $GITHUB_TOKEN
    file: /build/dnsdock.arm
    on:
      tags: true
  - provider: releases
    skip_cleanup: true
    api-key:
       secure: $GITHUB_TOKEN
    file: /build/dnsdock.arm64
    on:
      tags: true
  - provider: script
    script: /tmp/deploy_containers.sh
    on:
      tags: true
